app:
  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
      auth-uri: https://accounts.google.com/o/oauth2/auth
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET:}
      redirect-uri: ${KAKAO_REDIRECT_URI}
      auth-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET:}
      redirect-uri: ${NAVER_REDIRECT_URI}
      auth-uri: https://nid.naver.com/oauth2/authorize
      token-uri: https://nid.naver.com/oauth2/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,https://www.growgrammers.store,https://auth.easyappfactory.com,https://wedding.easyappfactory.com,https://admin-wedding.easyappfactory.com}
